module.exports = [
    {
        unit: "carrier",
        upgradeLevel: 2,
        localeName: "unit.carrier_2",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/carrier_2",
        move: 2,
        capacity: 6,
    },
    {
        unit: "cruiser",
        upgradeLevel: 2,
        localeName: "unit.cruiser_2",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/cruiser_2",
        spaceCombat: { hit: 6 },
        move: 3,
        capacity: 1,
    },
    {
        unit: "dreadnought",
        upgradeLevel: 2,
        localeName: "unit.dreadnought_2",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/dreadnought_2",
        move: 2,
        spaceCombat: { hit : 4 },
        bombardment: { hit: 4},
    },
    {
        unit: "fighter",
        upgradeLevel: 2,
        localeName: "unit.fighter",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/fighter_2",
        spaceCombat: { hit: 8 },
        move: 2,
        requireCapacity: false,
    },
    {
        unit: "infantry",
        upgradeLevel: 2,
        localeName: "unit.infantry_2",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/infantry_2",
        groundCombat: { hit: 7 },
    },
    {
        unit: "space_dock",
        upgradeLevel: 2,
        localeName: "unit.space_dock_2",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/space_dock_2",
        production: -4,
    },
    {
        unit: "war_sun",
        upgradeLevel: 2,
        localeName: "unit.war_sun",
        triggerNsid: "card.technology.unit_upgrade:homebrew.little-omega/war_sun",
        disablePlanetaryShield: true,
        sustainDamage: true,
        bombardment: { dice: 3, hit: 3 },
        cost: 12,
        spaceCombat: { dice: 3, hit: 3 },
        move: 2,
        capacity: 6,
    },
]