const FACTION_DATA = [{
    faction: "axis",
    abilities: ["military_industrial_complex", "arms_dealers"],
    commodities: 5,
    home: 3209,
    leaders: {
        agents: ["shipmonger_zsknck"],
        commanders: ["designer_tckvsk"],
        heroes: ["demi-queen_mdcksssk"],
    },
    promissoryNotes: ["industry_secrets"],
    icon: "discordant-discordant/faction-icons/axis.png",
    source: "homebrew_discordant_stars",
    startingTech: ["sarween_tools, ai_development_algorithm"],
    startingUnits: {
        carrier: 1,
        cruiser: 1,
        fighter: 2,
        infantry: 4,
        dreadnought: 1,
        pds: 1,
        space_dock: 1,
    },
    techs: [
        "rift_engines",
        "emergency_deployment",
    ],
    units: [
        "bearer_of_havens",
        "forgetender",
    ],
    unpackExtra: [
        {
            tokenNsid: "card.promissory.axis:homebrew.discordant-stars/axis_order_dreadnought",
            tokenCount: 2,
        },
        {
            tokenNsid: "card.promissory.axis:homebrew.discordant-stars/axis_order_carrier",
            tokenCount: 2,
        },
        {
            tokenNsid: "card.promissory.axis:homebrew.discordant-stars/axis_order_cruiser",
            tokenCount: 2,
        },
        {
            tokenNsid: "card.promissory.axis:homebrew.discordant-stars/axis_order_destroyers",
            tokenCount: 2,
        },
    ],
},
{
    faction: "celdauri",
    abilities: ["projection_of_power", "industrialists"],
    commodities: 4,
    home: 3219,
    leaders: {
        agents: ["george nobin"],
        commanders: ["henry storcher"],
        heroes: ["titus_flavius"],
    },
    promissoryNotes: ["trade_alliance"],
    icon: "discordant-stars/faction-icons/celdauri.png",
    source: "homebrew_discordant_stars",
    startingTech: [],
    startingUnits: {
        carrier: 1,
        destroyer: 1,
        fighter: 4,
        infantry: 3,
        pds: 1,
        space_dock: 1,
    },
    techs: ["emergency_mobilization_protocols"],
    units: [
        "supremacy",
        "trade_port",
        "trade_port_2",
        "minuteman",
    ],
    unpackExtra: [
        {
            tokenNsid: "token.unit:homebrew.discordant-stars.space_dock/celdauri",
        },
    ],
},
{
    faction: "cymiae",
    abilities: [
        "autonetic_memory",
        "cybernetic_madness"
    ],
    commodities: 3,
    home: 3213,
    leaders: {
        agents: ["skhot_unit_x-12"],
        commanders: ["koryl_ferax"],
        heroes: ["the_voice_united"],
    },
    promissoryNotes: ["algorithmic_replication"],
    icon: "discordant-stars/faction-icons/cymiae.png",
    source: "homebrew_discordant_stars",
    startingTech: ["neural_motivator", "ai_development_algorithm"],
    startingUnits: {
        carrier: 1,
        destroyer: 1,
        fighter: 2,
        infantry: 3,
        dreadnought: 1,
        space_dock: 1,
    },
    techs: ["recursive_worm"],
    units: [
        "reprocessor_alpha",
        "unholy_abomination",
        "unholy_abomination_2",
        "revenant"
    ],
},
{
    faction: "dihmohn",
    abilities: ["capital_fleet", "migrant_fleet", "flotilla"],
    commodities: 3,
    home: 3218,
    leaders: {
        agents: ["jgin_faru"],
        commanders: ["clona_bathru"],
        heroes: ["verrisus_ypru"],
    },
    promissoryNotes: ["combat_drills"],
    icon: "discordant-stars/faction-icons/dihmohn.png",
    source: "homebrew_discordant_stars",
    startingTech: ["dark-energy_tap", "scanlink_drone_network"],
    startingUnits: {
        dreadnought: 2,
        destroyers: 2,
        fighter: 2,
        mech: 1,
        infantry: 2,
        space_dock: 1,
    },
    techs: ["impressment_programs"],
    units: [
        "maximus",
        "aegis",
        "aegis_2",
        "repairitor",
    ],
},
{
    faction: "freesystems",
    abilities: [
        "rally_to_the_cause",
        "diplomats",
        "free_people",
    ],
    commodities: 3,
    home: 3202,
    leaders: {
        agents: ["cordo_haved"],
        commanders: ["president_cyhn"],
        heroes: ["count_otto_pmay"],
    },
    promissoryNotes: [""],
    icon: "discordant-stars/faction-icons/freesystems.png",
    source: "homebrew_discordant_stars",
    startingTech: ["psychoarchaeology"],
    startingUnits: {
        carrier: 1,
        cruiser: 2,
        fighter: 2,
        infantry: 4,
        pds: 1,
        space_dock: 1,
    },
    techs: ["envoy_network", "covert_strike_teams"],
    units: [
        "vox",
        "liberator",
    ],
    unpackExtra: [
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.heart_of_rebellion/freesystems",
            tokenCount: 0,
        },
    ],
},
{
    faction: "florzen",
    abilities: [
        "mercenaries",
        "data_leak",
        "black_markets",
    ],
    commodities: 4,
    home: 3217,
    leaders: {
        agents: ["sal_gavda"],
        commanders: ["quaxdol_junitas"],
        heroes: ["banua_gowen"],
    },
    promissoryNotes: ["blackmail_programs"],
    icon: "discordant-stars/faction-icons/florzen.png",
    source: "homebrew_discordant_stars",
    startingTech: ["neural_motivator", "scanlink_drone_network"],
    startingUnits: {
        carrier: 2,
        fighter: 4,
        infantry: 4,
        space_dock: 1,
    },
    techs: ["", ""],
    units: [
        "man_o_war",
        "corsair",
        "corsair_2",
        "privateer"
    ],
},
{
    faction: "ghemina",
    abilities: [
        "the_lady_and_the_lord",
        "rule_of_two",
    ],
    commodities: 2,
    home: 3205,
    leaders: {
        agents: ["skarvald_and_torvar"],
        commanders: ["jarl_vel_and_jarl_jotrun"],
        heroes: ["korela", "kantrus"],
    },
    promissoryNotes: ["raid_leaders"],
    icon: "discordant-stars/faction-icons/ghemina.png",
    source: "homebrew_discordant_stars",
    startingTech: ["psychoarchaelogy, dark_energy_tap"],
    startingUnits: {
        carrier: 2,
        destroyer: 1,
        fighter: 3,
        infantry: 3,
        space_dock: 2,
    },
    techs: ["war_song_implants"],
    units: [
        "the lady",
        "the lord",
        "combat_transport",
        "combat_transport_2",
        "jotun",
    ],
    unpackExtra: [
        {
            tokenNsid: "token.unit:homebrew.discordant-stars.lord_flagship/ghemina",
        },
        {
            tokenNsid: "card.unit:homebrew.discordant-stars.lord_flagship/ghemina",
        },
    ],
},
{
    faction: "ilyxum",
    abilities: [
        "oracle_ai",
        "limited_vision",
        "probability_algorithms",
    ],
    commodities: 3,
    home: 3208,
    leaders: {
        agents: ["clodho"],
        commanders: ["lachis"],
        heroes: ["atropha"],
    },
    promissoryNotes: ["read_the_fates"],
    icon: "discordant-stars/faction-icons/ilyxum.png",
    source: "homebrew_discordant_stars",
    startingTech: ["scanlink_drone_network", "ai_development_algorithm"],
    startingUnits: {
        carrier: 1,
        destroyers: 2,
        fighter: 2,
        infantry: 4,
        pds: 1,
        space_dock: 1,
    },
    techs: ["psychographics", "sentient_datapool"],
    units: [
        "nemsys",
        "iledrith",
    ],
},
{
    faction: "kollecc",
    abilities: [
        "cloaked_fleets",
        "shroud_of_lith",
        "treasure_hunters",
    ],
    commodities: 3,
    home: 3223,
    leaders: {
        agents: ["captain dust"],
        commanders: ["kado s’mah-qar"],
        heroes: ["dorrahn griphyn"],
    },
    promissoryNotes: ["ai_survey"],
    icon: "discordant-stars/faction-icons/kollecc.png",
    source: "homebrew_discordant_stars",
    startingTech: ["scanlink_drone_network"],
    startingUnits: {
        carrier: 2,
        cruiser: 1,
        fighter: 2,
        infantry: 4,
        space_dock: 1,
    },
    techs: ["seeker_drones", "shrouded_skirmishers"],
    units: [
        "nightingale_v",
        "nightshade_vanguard",
    ],
},
{
    faction: "kortali",
    abilities: [
        "fervor",
        "ruthless",
    ],
    commodities: 3,
    home: 3204,
    leaders: {
        agents: ["queen_lucreia"],
        commanders: ["queen_lorena"],
        heroes: ["queen_nadalia"],
    },
    promissoryNotes: ["blessing_of_the_queens"],
    icon: "discordant-stars/faction-icons/kortali.png",
    source: "homebrew_discordant_stars",
    startingTech: ["psychoarchaeology", "plasma_scoring"],
    startingUnits: {
        carrier: 2,
        cruiser: 1,
        fighter: 2,
        infantry: 4,
        pds: 1,
        space_dock: 1,
    },
    techs: ["tempest_drive", "deliverance_engine"],
    units: [
        "magistrate",
        "justicar",
    ],
},
{
    faction: "lizho",
    abilities: [
        "cunning",
        "subterfuge",
    ],
    commodities: 3,
    home: 3203,
    leaders: {
        agents: ["vasra_ivo"],
        commanders: ["dhume_tathu"],
        heroes: ["khaz-rin_li-zho"],
    },
    promissoryNotes: ["trusted_counselor"],
    icon: "discordant-stars/faction-icons/lizho.png",
    source: "homebrew_discordant_stars",
    startingTech: ["psychoarchaeology", "antimass_deflectors"],
    startingUnits: {
        carrier: 2,
        destroyer: 1,
        fighter: 3,
        infantry: 4,
        pds: 1,
        space_dock: 1,
    },
    techs: ["wraith engine"],
    units: [
        "silence_of_stars",
        "heavy_bomber",
        "heavy_bomber_2",
        "oro-zhin_elite",
    ],
    unpackExtra: [
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.trap_interference_grid/lizho",
        },
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.trap_minefields/lizho",
        },
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.trap_account_siphon/lizho",
        },
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.trap_gravitic_inhibitor/lizho",
        },
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.trap_feint/lizho",
        },
    ],
},
{
    faction: "ltokkkhrask",
    abilities: [
        "lithoids",
        "garden_worlds",
        "meteor_slings",
    ],
    commodities: 2,
    home: 3222,
    leaders: {
        agents: ["udosh_brtul"],
        commanders: ["hkot_tokal"],
        heroes: ["vehl-tikar"],
    },
    promissoryNotes: ["stone_speakers"],
    icon: "discordant-stars/faction-icons/ltokkkhrask.png",
    source: "homebrew_discordant_stars",
    startingTech: ["scanlink drone network", "plasma scoring"],
    startingUnits: {
        cruiser: 3,
        fighter: 1,
        infantry: 3,
        pds: 1,
        space_dock: 1,
    },
    techs: ["stones_embrace"],
    units: [
        "splintering_gale",
        "shattered_sky",
        "shattered_sky_2",
        "megalith",
    ],
},
{
    faction: "mirveda",
    abilities: [
        "privileged_citizenry",
        "combat_drones",
    ],
    commodities: 3,
    home: 3221,
    leaders: {
        agents: ["logic_machina"],
        commanders: ["assault_machina"],
        heroes: ["wrath_machina"],
    },
    promissoryNotes: ["rapid_assembly"],
    icon: "discordant-stars/faction-icons/mirveda.png",
    source: "homebrew_discordant_stars",
    startingTech: ["ai_development_algorithm"],
    startingUnits: {
        carrier: 2,
        cruiser: 1,
        fighter: 5,
        infantry: 2,
        pds: 1,
        space_dock: 1,
    },
    techs: ["orbital_defense_grid"],
    units: [
        "nexus",
        "gauss_cannon",
        "gauss_cannon_2",
        "javelin",
    ],
},
{
    faction: "mortheus",
    abilities: [
        "facsimile",
        "illusory_presence",
    ],
    commodities: 3,
    home: 2307,
    leaders: {
        agents: ["walik"],
        commanders: ["komat"],
        heroes: ["bayan"],
    },
    promissoryNotes: ["secrets_of_the_weave"],
    icon: "discordant-stars/faction-icons/mortheus.png",
    source: "homebrew_discordant_stars",
    startingTech: ["dark_energy_tap", "sarween_tools"],
    startingUnits: {
        dreadnought: 1,
        carrier: 1,
        destroyer: 1,
        fighter: 2,
        infantry: 3,
        space_dock: 1,
    },
    techs: ["fractal_plating", "fabrication_grid"],
    units: [
        "particle_sieve",
        "duuban",
    ],
},
{
    faction: "mykomentori",
    abilities: [
        "prescient_memories",
        "divination",
        "necrophage",
    ],
    commodities: 1,
    home: 3211,
    leaders: {
        agents: ["lactarius_indigo"],
        commanders: ["amanita_muscaria"],
        heroes: ["coprinus_comatus"],
    },
    promissoryNotes: ["gift_of_insight"],
    icon: "discordant-stars/faction-icons/mykomentori.png",
    source: "homebrew_discordant_stars",
    startingTech: ["predictive_intelligence"],
    startingUnits: {
        carrier: 2,
        cruiser: 1,
        fighter: 1,
        infantry: 6,
        space_dock: 1,
    },
    techs: ["psychoactive_armaments"],
    units: [
        "psyclobea_qarnyx",
        "mycelium_ring",
        "mycelium_ring_2",
        "amandia_pholdis",
    ],
    unpackExtra: [
        {
            tokenNsid: "dice:homebrew.discordant-stars.omen/mykomentori",
            tokenCount: 4,
        },
        {
            tokenNsid: "token.commodity:homebrew.discordant-stars.commodity_2/mykomentori",
        },
        {
            tokenNsid: "token.commodity:homebrew.discordant-stars.commodity_3/mykomentori",
        },
        {
            tokenNsid: "token.commodity:homebrew.discordant-stars.commodity_4/mykomentori",
        },
        {
            tokenNsid: "tile.system:homebrew.discordant-stars.mykomentori/nova_seed",
        },
    ],
},
{
    faction: "nivyn",
    abilities: [
        "celestial_guides",
        "singularity_point",
        "voidsailors",
    ],
    commodities: 3,
    home: 3220,
    leaders: {
        agents: ["suldhan_wraeg"],
        commanders: ["thussad_krath"],
        heroes: ["kwill_drakkon"],
    },
    promissoryNotes: ["nivyn_guidance"],
    icon: "discordant-stars/faction-icons/nivyn.png",
    source: "homebrew_discordant_stars",
    startingUnits: {
        carrier: 1,
        cruiser: 1,
        dreadnought: 1,
        fighter: 3,
        infantry: 3,
        mech: 1,
        space_dock: 1,
    },
    techs: ["voidwake_missiles"],
    units: [
        "eradica",
        "voidflare_warden",
        "voidflare_warden_2",
    ],
    unpackExtra: [
        {
            tokenNsid: "token.system:homebrew.discordant-stars.wound/nivyn",
        },
    ],
},
{
    faction: "olradin",
    abilities: [
        "policies",
    ],
    commodities: 3,
    home: 3210,
    leaders: {
        agents: ["baggil_wildpaw"],
        commanders: ["knak_halfear"],
        heroes: ["pahn_silverfur"],
    },
    promissoryNotes: ["incite_revolution"],
    icon: "discordant-stars/faction-icons/olradin.png",
    source: "homebrew_discordant_stars",
    startingTech: ["psychoarchaeology", "scanlink_drone_network"],
    startingUnits: {
        carrier: 2,
        cruiser: 1,
        fighter: 3,
        infantry: 4,
        space_dock: 1,
    },
    techs: ["false_flag_operations", "geosympathic_impeller"],
    units: [
        "rallypoint",
        "exemplar",
    ],
    unpackExtra: [
        {
            tokenNsid: "card.ability:homebrew.discordant-stars.olradin/the_people",
        },
        {
            tokenNsid: "card.ability:homebrew.discordant-stars.olradin/the_environment",
        },
        {
            tokenNsid: "card.ability:homebrew.discordant-stars.olradin/the_economy",
        },
    ],
},
{
    faction: "rhodun",
    abilities: [
        "conspirators",
        "ancient_knowledge",
    ],
    commodities: 3,
    home: 3224,
    leaders: {
        agents: ["priestess tuh"],
        commanders: ["bishop ulin"],
        heroes: ["saint_binal"],
    },
    promissoryNotes: ["favor_of_rhodun"],
    icon: "discordant-stars/faction-icons/rhodun.png",
    source: "homebrew_discordant_stars",
    startingTech: [],
    startingUnits: {
        carrier: 1,
        cruiser: 1,
        fighter: 3,
        infantry: 4,
        destroyer: 1,
        space_dock: 1,
    },
    techs: ["sanctification field", "pilgrimage_beacons"],
    units: [
        "reckoning",
        "templar",
    ],
},
{
    faction: "rohdhna",
    abilities: [
        "industrious",
        "recycled_materials",
        "orbital_foundries",
    ],
    commodities: 4,
    home: 3214,
    leaders: {
        agents: ["rond_briay"],
        commanders: ["b-unit_205643a"],
        heroes: ["roh_vhin_dhna_mk4"],
    },
    promissoryNotes: ["automatons"],
    icon: "discordant-stars/faction-icons/rohdhna.png",
    source: "homebrew_discordant_stars",
    startingTech: ["psychoarchaeology", "sarween_tools"],
    startingUnits: {
        carrier: 1,
        cruiser: 1,
        fighter: 2,
        infantry: 4,
        dreadnought: 1,
        pds: 1,
        space_dock: 1,
    },
    techs: ["contractual obligations"],
    units: [
        "ky_vir",
        "terrafactory",
        "terrafactory_2",
        "autofabricator",
    ],
    unpackExtra: [
        {
            tokenNsid: "token.attachment:homebrew.discordant-stars.automatons/rohdhna",
        },
    ],
},
{
    faction: "tnelis",
    abilities: [
        "plausible_deniability",
        "information_brokers",
        "stealth_insertion",
    ],
    commodities: 2,
    home: 3212,
    leaders: {
        agents: ["davish_the_tixian_s_norri"],
        commanders: ["fillipo_the_comm-czar_rois"],
        heroes: ["turra_the_vigh-king_sveyar"],
    },
    promissoryNotes: ["plots_within_plots"],
    icon: "discordant-stars/faction-icons/tnelis.png",
    source: "homebrew_discordant_stars",
    startingTech: [],
    startingUnits: {
        carrier: 1,
        destroyer: 2,
        fighter: 2,
        infantry: 4,
        pds: 1,
        space_dock: 1,
    },
    techs: ["daedalon_flight_system"],
    units: [
        "principia aneris",
        "daedalon",
        "blockade_runner",
        "blockade_runner_2",
        "",
    ],
},
{
    faction: "vaden",
    abilities: [
        "fine_print",
        "collateralized_loans",
        "binding_debts",
    ],
    commodities: 3,
    home: 3206,
    leaders: {
        agents: ["yudri_sukhov"],
        commanders: ["komdar_borodin"],
        heroes: ["putriv_sirvonsk"],
    },
    promissoryNotes: [""],
    icon: "discordant-stars/faction-icons/vaden.png",
    source: "homebrew_discordant_stars",
    startingTech: [],
    startingUnits: {
        dreadnought: 1,
        carrier: 1,
        cruiser: 1,
        fighter: 2,
        infantry:34,
        space_dock: 1,
    },
    techs: ["midas turbine", "krovoz_strike_teams"],
    units: [
        "aurum_vadra",
        "komdar_borodin",
        "putriv_sirvonsk",
        "collector",
    ],
},
{
    faction: "vaylerian",
    abilities: [
        "cargo raiders",
        "scour",
        "raze",
    ],
    commodities: 2,
    home: 3216,
    leaders: {
        agents: ["yvin_korduul"],
        commanders: ["pyndil_gonsuul"],
        heroes: ["dyln_harthuul"],
    },
    promissoryNotes: ["clans_favor"],
    icon: "discordant-stars/faction-icons/vaylerian.png",
    source: "homebrew_discordant_stars",
    startingTech: ["neural_motivator", "dark_energy_tap"],
    startingUnits: {
        carrier: 1,
        cruiser: 1,
        fighter: 3,
        infantry: 3,
        pds: 1,
        space_dock: 1,
    },
    techs: ["scavenger_exos"],
    units: [
        "lost_cause",
        "raider",
        "raider_2",
        "eclipse",
    ],
},
{
    faction: "veldyr",
    abilities: [
        "corporate_entity",
        "holding_company",
        "targeted_acquisition",
    ],
    commodities: 4,
    home: 3201,
    leaders: {
        agents: ["solis_morden"],
        commanders: ["vera_khage"],
        heroes: ["auberon_elyrin"],
    },
    promissoryNotes: ["branch_office-tax_haven", "branch_office-broadcast_hub", "branch_office-reserve_bank", "branch_office-orbital_shipyard"],
    icon: "discordant-stars/faction-icons/veldyr.png",
    source: "homebrew_discordant_stars",
    startingTech: ["dark_energy_tap", "ai_development_algorithm"],
    startingUnits: {
        dreadnought: 1,
        carrier: 1,
        destroyer: 1,
        fighter: 2,
        infantry: 4,
        space_dock: 1,
        pds: 1,
    },
    techs: ["seidr_project"],
    units: [
        "richtyrian",
        "lancer",
        "lancer_2",
        "aurora_stormcaller",
    ],
},
{
    faction: "zelian",
    abilities: [
        "obsessive_designs",
        "biophobic",
        "paranoia",
    ],
    commodities: 3,
    home: 3215,
    leaders: {
        agents: ["zelian_a"],
        commanders: ["zelian_b"],
        heroes: ["zelian_r"],
    },
    promissoryNotes: ["hyperkinetic_ordinance"],
    icon: "discordant-stars/faction-icons/zelian.png",
    source: "homebrew_discordant_stars",
    startingTech: ["anti-mass_deflectors, ai_development_algorithm"],
    startingUnits: {
        dreadnought: 1,
        carrier: 1,
        destroyer: 1,
        fighter: 1,
        infantry: 5,
        space_dock: 1,
        pds: 1,
    },
    techs: ["shard_volley"],
    units: [
        "world-cracker",
        "impactor",
        "impactor_2",
        "collider",
    ],
    unpackExtra: [
        {
            tokenNsid: "tile.system:homebrew.discordant-stars.zelian/cataclysm",
        },
    ],
}]