// Incomplete Discordant Stars factions, exported from another platform.
module.exports = [
    {
        faction: "veldyr",
        abilities: [
            "corporate_entity",
            "holding_company",
            "targeted_acquisition",
        ],
        commodities: 4,
        home: 3201,
        leaders: {
            agents: ["solis_morden"],
            commanders: ["vera_khage"],
            heroes: ["auberon_elyrin"],
        },
        promissoryNotes: [
            "branch_office_tax_haven",
            "branch_office_broadcast_hub",
            "branch_office_reserve_bank",
            "branch_office_orbital_shipyard",
        ],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["seidr_project"],
        units: [
            "richtyrian",
            "lancer_dreadnought",
            "lancer_dreadnought_2",
            "aurora_stormcaller",
        ],
    },
    {
        faction: "free_systems",
        abilities: ["rally_to_the_cause", "diplomats", "free_people"],
        commodities: 4,
        home: 3202,
        leaders: {
            agents: ["cordo_haved"],
            commanders: ["president_cyhn"],
            heroes: ["count_otto_pmay"],
        },
        promissoryNotes: ["broadcast_teams"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology"],
        startingUnits: {
            carrier: 1,
            cruiser: 2,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["envoy_network", "covert_strike_teams"],
        units: ["vox", "liberator"],
    },
    {
        faction: "lizho",
        abilities: ["cunning", "subterfuge"],
        commodities: 3,
        home: 3203,
        leaders: {
            agents: ["vasra_ivo"],
            commanders: ["dume_tathu"],
            heroes: ["khazrin_lizho"],
        },
        promissoryNotes: ["trusted_counselor"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "antimass_deflectors"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 3,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["wraith_engine"],
        units: [
            "silence_of_stars",
            "heavy_bomber",
            "heavy_bomber_2",
            "orozhin_elite",
        ],
    },
    {
        faction: "khrask",
        abilities: ["lithoids", "garden_worlds", "meteor_slings"],
        commodities: 2,
        home: 3204,
        leaders: {
            agents: ["udosh_brtul"],
            commanders: ["hkot_tokal"],
            heroes: ["vehl_tikar"],
        },
        promissoryNotes: ["stone_speakers"],
        source: "discordant_stars",
        startingTech: ["scanlink_drone_network", "plasma_scoring"],
        startingUnits: {
            cruiser: 3,
            fighter: 1,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: ["stones_embrace"],
        units: [
            "splintering_gale",
            "shattered_sky",
            "shattered_sky_2",
            "megalith",
        ],
    },
    {
        faction: "ghemina",
        abilities: ["the_lady_the_lord", "rule_of_two"],
        commodities: 2,
        home: 3205,
        leaders: {
            agents: ["skarvald_torvar"],
            commanders: ["jarl_vel_jarl_jotrun"],
            heroes: ["korela", "kantrus"],
        },
        promissoryNotes: ["raid_leaders"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "dark_energy_tap"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 3,
            infantry: 3,
            spacedock: 2,
        },
        techs: ["war_song_implants"],
        units: [
            "the_lady_the_lord",
            "combat_transport",
            "combat_transport_2",
            "jotun",
        ],
    },
    {
        faction: "vaden",
        abilities: ["fine_print", "collateralized_loans", "binding_debts"],
        commodities: 3,
        home: 3206,
        leaders: {
            agents: ["yudri_sukhov"],
            commanders: ["komdar_borodin"],
            heroes: ["putriv_sirvonsk"],
        },
        promissoryNotes: ["vaden_handshake"],
        source: "discordant_stars",
        startingTech: [
            "neural_motivator",
            "antimass_deflectors",
            "sarween_tools",
        ],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["midas_turbine", "krovoz_strike_teams"],
        units: ["aurum_vadra", "collector"],
    },
    {
        faction: "mortheus",
        abilities: ["facsimile", "illusory_presence"],
        commodities: 3,
        home: 3207,
        leaders: {
            agents: ["walik"],
            commanders: ["komat"],
            heroes: ["bayan"],
        },
        promissoryNotes: ["secrets_of_the_weave"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "sarween_tools"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["fractal_plating", "fabrication_grid"],
        units: ["particle_sieve", "duuban"],
    },
    {
        faction: "ilyxum",
        abilities: ["oracle_ai", "limited_vision", "probability_algorithms"],
        commodities: 3,
        home: 3208,
        leaders: {
            agents: ["clodho"],
            commanders: ["lachis"],
            heroes: ["atropha"],
        },
        promissoryNotes: ["read_the_fates"],
        source: "discordant_stars",
        startingTech: ["scanlink_drone_network", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["psychographics", "sentient_datapool"],
        units: ["nemsys", "iledrith"],
    },
    {
        faction: "axis",
        abilities: ["military_industrial_complex", "arms_dealers"],
        commodities: 5,
        home: 3209,
        leaders: {
            agents: ["shipmonger_zsknck"],
            commanders: ["designer_tckvsk"],
            heroes: ["demiqueen_mdckssk"],
        },
        promissoryNotes: ["industry_secrets"],
        source: "discordant_stars",
        startingTech: ["sarween_tools", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["rift_engines", "emergency_deployment"],
        units: ["bearer_of_heavens", "forgetender"],
    },
    {
        faction: "olradin",
        abilities: ["policies"],
        commodities: 3,
        home: 3210,
        leaders: {
            agents: ["baggil_wildpaw"],
            commanders: ["knak_halfear"],
            heroes: ["pahn_silverfur"],
        },
        promissoryNotes: ["incite_revolution"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "scanlink_drone_network"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 3,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["false_flag_operations", "geosympathic_impeller"],
        units: ["rallypoint", "exemplar"],
    },
    {
        faction: "mykomentori",
        abilities: ["prescient_memories", "divination", "necrophage"],
        commodities: 1,
        home: 3211,
        leaders: {
            agents: ["lactarius_indigo"],
            commanders: ["amanita_muscaria"],
            heroes: ["coprinus_comatus"],
        },
        promissoryNotes: ["gift_of_insight"],
        source: "discordant_stars",
        startingTech: ["predictive_intelligence"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 1,
            infantry: 6,
            spacedock: 1,
        },
        techs: ["psychoactive_armaments"],
        units: [
            "psyclobea_qarnyx",
            "amandia_pholdis",
            "mycelium_ring",
            "mycelium_ring_2",
        ],
    },
    {
        faction: "tnelis",
        abilities: [
            "plausible_deniability",
            "information_brokers",
            "stealth_insertion",
        ],
        commodities: 2,
        home: 3212,
        leaders: {
            agents: ["davish_snorri"],
            commanders: ["fillipo_rois"],
            heroes: ["turra_sveyar"],
        },
        promissoryNotes: ["plots_within_plots"],
        source: "discordant_stars",
        startingTech: [
            "neural_motivator",
            "antimass_deflectors",
            "plasma_scoring",
        ],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["deadalon_flight_system"],
        units: ["principia_aneris", "blockade_runner", "daedalon"],
    },
    {
        faction: "cymiae",
        abilities: ["autonetic_memory", "cybernetic_madness"],
        commodities: 3,
        home: 3213,
        leaders: {
            agents: ["skhot_unit_x12"],
            commanders: ["koryl_ferax"],
            heroes: ["the_voice_united"],
        },
        promissoryNotes: ["algorithmic_replication"],
        source: "discordant_stars",
        startingTech: ["neural_motivator", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["recursive_worm"],
        units: [
            "reprocessor_alpha",
            "unholy_abomination",
            "unholy_abomination_2",
            "revenant",
        ],
    },
    {
        faction: "rohdhna",
        abilities: ["industrious", "recycled_materials", "orbital_foundries"],
        commodities: 4,
        home: 3214,
        leaders: {
            agents: ["rond_briay"],
            commanders: ["bunit_205643a"],
            heroes: ["rohvhin_dhna_mk4"],
        },
        promissoryNotes: ["automatons"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "sarween_tools"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 3,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["contractual_obligations"],
        units: ["kyvir", "terrafactory", "terrafactory_2", "autofabricator"],
    },
    {
        faction: "zelian",
        abilities: ["obsessive_designs", "biophobic", "paranoia"],
        commodities: 2,
        home: 3215,
        leaders: {
            agents: ["zelian_a"],
            commanders: ["zelian_b"],
            heroes: ["zelian_r"],
        },
        promissoryNotes: ["hyperkinetic_ordinance"],
        source: "discordant_stars",
        startingTech: ["antimass_deflectors", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 1,
            infantry: 5,
            pds: 1,
            spacedock: 1,
        },
        techs: ["shard_volley"],
        units: ["worldcracker", "impactor", "impactor_2", "collider"],
    },
    {
        faction: "vaylerian",
        abilities: ["cargo_raiders", "scour", "raze"],
        commodities: 2,
        home: 3216,
        leaders: {
            agents: ["yvin_korduul"],
            commanders: ["pyndil_gonsuul"],
            heroes: ["dyln_harthuul"],
        },
        promissoryNotes: ["clans_favor"],
        source: "discordant_stars",
        startingTech: ["neural_motivator", "dark_energy_tap"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            destroyer: 1,
            fighter: 3,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: ["scavenger_exos"],
        units: ["lost_cause", "raider", "raider_2", "eclipse"],
    },
    {
        faction: "florzen",
        abilities: ["mercenaries", "data_leak", "black_markets"],
        commodities: 4,
        home: 3217,
        leaders: {
            agents: ["sal_gavda"],
            commanders: ["quaxdol_junitas"],
            heroes: ["banua_gowen"],
        },
        promissoryNotes: ["underground_market"],
        source: "discordant_stars",
        startingTech: ["neural_motivator", "scanlink_drone_network"],
        startingUnits: {
            carrier: 2,
            fighter: 4,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["blackmail_programs"],
        units: ["man_o_war", "corsair", "corsair_2", "privateer"],
    },
    {
        faction: "dihmohn",
        abilities: ["capital_fleet", "migrant_fleet", "flotilla"],
        commodities: 2,
        home: 3218,
        leaders: {
            agents: ["jgin_faru"],
            commanders: ["clona_bathru"],
            heroes: ["verrisus_ypru"],
        },
        promissoryNotes: ["combat_drills"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "scanlink_drone_network"],
        startingUnits: {
            destroyer: 2,
            dreadnought: 2,
            fighter: 2,
            infantry: 2,
            mech: 1,
            spacedock: 1,
        },
        techs: ["impressment_programs"],
        units: ["maximus", "aegis", "aegis_2", "repairitor"],
    },
    {
        faction: "celdauri",
        abilities: ["projection_of_power", "industrialists"],
        commodities: 4,
        home: 3219,
        leaders: {
            agents: ["george_nobin"],
            commanders: ["henry_storcher"],
            heroes: ["titus_flavius"],
        },
        promissoryNotes: ["trade_alliance"],
        source: "discordant_stars",
        startingTech: [
            "antimass_deflectors",
            "sarween_tools",
            "plasma_scoring",
        ],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 4,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: ["emergency_mobilization_protocols"],
        units: ["supremacy", "trade_port", "trade_port_2", "minuteman"],
    },
    {
        faction: "nivyn",
        abilities: ["celestial_guides", "singularity_point", "voidsailors"],
        commodities: 3,
        home: 3220,
        leaders: {
            agents: ["suldhan_wraeg"],
            commanders: ["thussad_krath"],
            heroes: ["krill_drakkon"],
        },
        promissoryNotes: ["nivyn_guidance"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "plasma_scoring"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 3,
            infantry: 3,
            mech: 1,
            spacedock: 1,
        },
        techs: ["voidwake_missles"],
        units: ["eradica", "voidflare_warden", "voidflare_warden_2"],
    },
    {
        faction: "mirveda",
        abilities: ["priviledged_citizenry", "combat_drones"],
        commodities: 3,
        home: 3221,
        leaders: {
            agents: ["logic_machina"],
            commanders: ["assault_machina"],
            heroes: ["wrath_machina"],
        },
        promissoryNotes: ["rapid_excavation"],
        source: "discordant_stars",
        startingTech: ["ai_development_algorithm"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 5,
            infantry: 2,
            pds: 1,
            spacedock: 1,
        },
        techs: ["orbital_defense_grid"],
        units: ["nexus", "gauss_cannon", "gauss_cannon_2", "javelin"],
    },
    {
        faction: "kortali",
        abilities: ["zealous", "ruthless"],
        commodities: 3,
        home: 3222,
        leaders: {
            agents: ["queen_lucreia"],
            commanders: ["queen_lorena"],
            heroes: ["queen_nadalia"],
        },
        promissoryNotes: ["blessing_of_the_queens"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "plasma_scoring"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["tempest_drive", "deliverance_engine"],
        units: ["magistrate", "justicar"],
    },
    {
        faction: "kollecc",
        abilities: ["cloaked_fleet", "shroud_of_lith", "treasure_hunters"],
        commodities: 3,
        home: 3223,
        leaders: {
            agents: ["captain_dust"],
            commanders: ["kado_smahqar"],
            heroes: ["dorrahn_griphyn"],
        },
        promissoryNotes: ["ai_survey"],
        source: "discordant_stars",
        startingTech: ["scanlink_drone_network"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["seeker_drones", "shrouded_skirmishers"],
        units: ["nightingale_v", "nightshade_vanguard"],
    },
    {
        faction: "rhodun",
        abilities: ["conspirators", "ancient_knowledge"],
        commodities: 3,
        home: 3224,
        leaders: {
            agents: ["priestess_tuh"],
            commanders: ["bishop_ulin"],
            heroes: ["saint_binal"],
        },
        promissoryNotes: ["favor_of_rhodun"],
        source: "discordant_stars",
        startingTech: ["biostims"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            destroyer: 1,
            fighter: 3,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["sanctification_field", "pilgrimage_beacons"],
        units: ["reckoning", "templar"],
    },
    {
        faction: "edyn",
        abilities: [
            "enlightenment",
            "grace",
            "royal_decree",
        ],
        commodities: 3,
        home: 3225,
        leaders: {
            agents: ["allant"],
            commanders: ["kadryn"],
            heroes: ["midir"],
        },
        promissoryNotes: ["edyn_diplomatic_support"],
        source: "discordant_stars",
        startingTech: ["pscyhoarchaeology", "dark_energy_tap", "scanlink_drone_network", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 3,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: ["unity_algorithm", "encrypted_trade_hub"],
        units: ["kaliburn", "runebearer"],
    },
    {
        faction: "kjalengard",
        abilities: [
            "heroic_tales",
            "for_glory",
            "military_engineers",
        ],
        commodities: 3,
        home: 3226,
        leaders: {
            agents: ["merkismathr_asvand"],
            commanders: ["sdallari_tvungovot"],
            heroes: ["ygegnad_the_thunder"],
        },
        promissoryNotes: ["vassalage"],
        source: "discordant_stars",
        startingTech: [],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 4,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["unity_algorithm", "encrypted_trade_hub"],
        units: ["hulgades_hammer", "star_dragon", "star_dragon_2", "skald"],
    },
    {
        faction: "bentor",
        abilities: [
            "secret_maps",
            "fortune_seekers",
            "ancient_blueprints",
        ],
        commodities: 2,
        home: 3227,
        leaders: {
            agents: ["coo_mgur"],
            commanders: ["cmo_ranc"],
            heroes: ["ceo_ken_tucc"],
        },
        promissoryNotes: ["encryption_key"],
        source: "discordant_stars",
        startingTech: ["pscyhoarchaeology", "dark_energy_tap", "scanlink_drone_network"],
        startingUnits: {
            carrier: 1,
            cruiser: 2,
            fighter: 3,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["broker_network", "merged_replicators"],
        units: ["wayfinder", "auctioneer"],
    },
    {
        faction: "nokar",
        abilities: [
            "hired_guns",
            "private_fleet",
            "desperados",
        ],
        commodities: 4,
        home: 3228,
        leaders: {
            agents: ["sal_sparrow"],
            commanders: ["jack_hallard"],
            heroes: ["starsails"],
        },
        promissoryNotes: ["nokar_navigator"],
        source: "discordant_stars",
        startingTech: ["pscyhoarchaeology", "dark_energy_tap", "ai_development_algorithm"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["local_contracts"],
        units: ["annah_regia", "sabre", "sabre_2", "freelance_outfit"],
    },
    {
        faction: "gledge",
        abilities: [
            "mantle_cracking",
            "celestial_reclamation",
            "deep_mining",
        ],
        commodities: 2,
        home: 3229,
        leaders: {
            agents: ["durran"],
            commanders: ["voldun"],
            heroes: ["gorthrim"],
        },
        promissoryNotes: ["gledge_base"],
        source: "discordant_stars",
        startingTech: ["pscyhoarchaeology", "scanlink_drone_network", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 3,
            infantry: 2,
            mech: 1,
            spacedock: 1,
        },
        techs: ["lightning_drives"],
        units: ["beg_bersha", "orion_platform", "orion_platform_2", "exodriller"],
    },
    {
        faction: "lanefir",
        abilities: [
            "a_new_edifice",
            "iconoclasm",
            "war_stories",
        ],
        commodities: 2,
        home: 3230,
        leaders: {
            agents: ["vassa_hagi"],
            commanders: ["master_halbert"],
            heroes: ["the_venerable"],
        },
        promissoryNotes: ["spoils_of_war"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "scanlink_drone_network", "ai_development_algorithm"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 2,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: ["spark_thrusters", "ats_armaments"],
        units: ["memory_of_dusk", "troubadour"],
    },
    {
        faction: "blex",
        abilities: [
            "contagion",
            "blight",
            "shared_misery",
        ],
        commodities: 2,
        home: 3231,
        leaders: {
            agents: ["tox"],
            commanders: ["silas_deriga"],
            heroes: ["speygh"],
        },
        promissoryNotes: ["blex_agents"],
        source: "discordant_stars",
        startingTech: ["daxcive_animators", "biostims"],
        startingUnits: {
            carrier: 1,
            dreadnought: 1,
            destroyer: 1,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["meldships"],
        units: ["auriga", "vector", "vector_2", "pustule"],
    },
    {
        faction: "ghoti",
        abilities: [
            "mobile_command",
            "spawning_grounds",
            "all_mothers_embrace",
        ],
        commodities: 4,
        home: 3232,
        leaders: {
            agents: ["becece"],
            commanders: ["ceie_dolegueaunm"],
            heroes: ["nmenmede"],
        },
        promissoryNotes: ["ghoti_relay"],
        source: "discordant_stars",
        startingTech: ["gravity_drive", "sling_relay"],
        startingUnits: {
            flagship: 1,
            cruiser: 1,
            fighter: 2,
            infantry: 3,
        },
        techs: ["networked_command", "parallel_production"],
        units: ["all_mother", "tioleombp"],
    },
    {
        faction: "kolume",
        abilities: [
            "starfall_gunnery",
            "deliberate_action",
            "meditation",
        ],
        commodities: 3,
        home: 3233,
        leaders: {
            agents: ["disciple_fran"],
            commanders: ["issac_of_sinci"],
            heroes: ["wonell_the_silent"],
        },
        promissoryNotes: ["combinatorial_bypass"],
        source: "discordant_stars",
        startingTech: ["graviton_laser_system", "predictive_intelligence"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["applied_biothermics", "omniscience_field"],
        units: ["halberd", "rook"],
    },
    {
        faction: "cheiran",
        abilities: [
            "teeming",
            "moult",
            "byssus",
        ],
        commodities: 3,
        home: 3234,
        leaders: {
            agents: ["operator_kkavras"],
            commanders: ["spc_Phquaiset"],
            heroes: ["thakt_clqua"],
        },
        promissoryNotes: ["carcinisation"],
        source: "discordant_stars",
        startingTech: ["magen_defense_grid", "self_assembly_routines"],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 3,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: ["unity_algorithm", "encrypted_trade_hub"],
        units: ["lithodax", "chitin_hulk", "chitin_hulk_2", "nauplius"],
    },
];
